//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://siat.impuestos.gob.bo/", ConfigurationName="ServiceReference1.ServicioFacturacion")]
    public interface ServicioFacturacion {
        
        // CODEGEN: Parameter 'RespuestaServicioFacturacion' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaServicioFacturacion")]
        WindowsFormsApp2.ServiceReference1.recepcionPaqueteFacturaResponse recepcionPaqueteFactura(WindowsFormsApp2.ServiceReference1.recepcionPaqueteFactura request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.recepcionPaqueteFacturaResponse> recepcionPaqueteFacturaAsync(WindowsFormsApp2.ServiceReference1.recepcionPaqueteFactura request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApp2.ServiceReference1.verificarComunicacionResponse verificarComunicacion(WindowsFormsApp2.ServiceReference1.verificarComunicacion request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.verificarComunicacionResponse> verificarComunicacionAsync(WindowsFormsApp2.ServiceReference1.verificarComunicacion request);
        
        // CODEGEN: Parameter 'RespuestaServicioFacturacion' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaServicioFacturacion")]
        WindowsFormsApp2.ServiceReference1.recepcionFacturaResponse recepcionFactura(WindowsFormsApp2.ServiceReference1.recepcionFactura request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.recepcionFacturaResponse> recepcionFacturaAsync(WindowsFormsApp2.ServiceReference1.recepcionFactura request);
        
        // CODEGEN: Parameter 'RespuestaServicioFacturacion' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaServicioFacturacion")]
        WindowsFormsApp2.ServiceReference1.validacionRecepcionMasivaFacturaResponse validacionRecepcionMasivaFactura(WindowsFormsApp2.ServiceReference1.validacionRecepcionMasivaFactura request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.validacionRecepcionMasivaFacturaResponse> validacionRecepcionMasivaFacturaAsync(WindowsFormsApp2.ServiceReference1.validacionRecepcionMasivaFactura request);
        
        // CODEGEN: Parameter 'RespuestaRecepcionAnexos' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaRecepcionAnexos")]
        WindowsFormsApp2.ServiceReference1.recepcionAnexosResponse recepcionAnexos(WindowsFormsApp2.ServiceReference1.recepcionAnexos request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.recepcionAnexosResponse> recepcionAnexosAsync(WindowsFormsApp2.ServiceReference1.recepcionAnexos request);
        
        // CODEGEN: Parameter 'RespuestaServicioFacturacion' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaServicioFacturacion")]
        WindowsFormsApp2.ServiceReference1.recepcionMasivaFacturaResponse recepcionMasivaFactura(WindowsFormsApp2.ServiceReference1.recepcionMasivaFactura request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.recepcionMasivaFacturaResponse> recepcionMasivaFacturaAsync(WindowsFormsApp2.ServiceReference1.recepcionMasivaFactura request);
        
        // CODEGEN: Parameter 'RespuestaServicioFacturacion' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaServicioFacturacion")]
        WindowsFormsApp2.ServiceReference1.verificacionEstadoFacturaResponse verificacionEstadoFactura(WindowsFormsApp2.ServiceReference1.verificacionEstadoFactura request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.verificacionEstadoFacturaResponse> verificacionEstadoFacturaAsync(WindowsFormsApp2.ServiceReference1.verificacionEstadoFactura request);
        
        // CODEGEN: Parameter 'RespuestaServicioFacturacion' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaServicioFacturacion")]
        WindowsFormsApp2.ServiceReference1.validacionRecepcionPaqueteFacturaResponse validacionRecepcionPaqueteFactura(WindowsFormsApp2.ServiceReference1.validacionRecepcionPaqueteFactura request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.validacionRecepcionPaqueteFacturaResponse> validacionRecepcionPaqueteFacturaAsync(WindowsFormsApp2.ServiceReference1.validacionRecepcionPaqueteFactura request);
        
        // CODEGEN: Parameter 'RespuestaServicioFacturacion' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaServicioFacturacion")]
        WindowsFormsApp2.ServiceReference1.anulacionFacturaResponse anulacionFactura(WindowsFormsApp2.ServiceReference1.anulacionFactura request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.anulacionFacturaResponse> anulacionFacturaAsync(WindowsFormsApp2.ServiceReference1.anulacionFactura request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudRecepcionPaquete : solicitudRecepcionFactura {
        
        private string cafcField;
        
        private int cantidadFacturasField;
        
        private long codigoEventoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cafc {
            get {
                return this.cafcField;
            }
            set {
                this.cafcField = value;
                this.RaisePropertyChanged("cafc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int cantidadFacturas {
            get {
                return this.cantidadFacturasField;
            }
            set {
                this.cantidadFacturasField = value;
                this.RaisePropertyChanged("cantidadFacturas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long codigoEvento {
            get {
                return this.codigoEventoField;
            }
            set {
                this.codigoEventoField = value;
                this.RaisePropertyChanged("codigoEvento");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionMasiva))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionPaquete))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudRecepcionFactura : solicitudRecepcion {
        
        private byte[] archivoField;
        
        private string fechaEnvioField;
        
        private string hashArchivoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] archivo {
            get {
                return this.archivoField;
            }
            set {
                this.archivoField = value;
                this.RaisePropertyChanged("archivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fechaEnvio {
            get {
                return this.fechaEnvioField;
            }
            set {
                this.fechaEnvioField = value;
                this.RaisePropertyChanged("fechaEnvio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string hashArchivo {
            get {
                return this.hashArchivoField;
            }
            set {
                this.hashArchivoField = value;
                this.RaisePropertyChanged("hashArchivo");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudAnulacion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudVerificacionEstado))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionAnexos))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudValidacionRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionFactura))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionMasiva))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionPaquete))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudRecepcion : modelDto {
        
        private int codigoAmbienteField;
        
        private int codigoDocumentoSectorField;
        
        private int codigoEmisionField;
        
        private int codigoModalidadField;
        
        private int codigoPuntoVentaField;
        
        private bool codigoPuntoVentaFieldSpecified;
        
        private string codigoSistemaField;
        
        private int codigoSucursalField;
        
        private string cufdField;
        
        private string cuisField;
        
        private long nitField;
        
        private int tipoFacturaDocumentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoAmbiente {
            get {
                return this.codigoAmbienteField;
            }
            set {
                this.codigoAmbienteField = value;
                this.RaisePropertyChanged("codigoAmbiente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoDocumentoSector {
            get {
                return this.codigoDocumentoSectorField;
            }
            set {
                this.codigoDocumentoSectorField = value;
                this.RaisePropertyChanged("codigoDocumentoSector");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int codigoEmision {
            get {
                return this.codigoEmisionField;
            }
            set {
                this.codigoEmisionField = value;
                this.RaisePropertyChanged("codigoEmision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int codigoModalidad {
            get {
                return this.codigoModalidadField;
            }
            set {
                this.codigoModalidadField = value;
                this.RaisePropertyChanged("codigoModalidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int codigoPuntoVenta {
            get {
                return this.codigoPuntoVentaField;
            }
            set {
                this.codigoPuntoVentaField = value;
                this.RaisePropertyChanged("codigoPuntoVenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoPuntoVentaSpecified {
            get {
                return this.codigoPuntoVentaFieldSpecified;
            }
            set {
                this.codigoPuntoVentaFieldSpecified = value;
                this.RaisePropertyChanged("codigoPuntoVentaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string codigoSistema {
            get {
                return this.codigoSistemaField;
            }
            set {
                this.codigoSistemaField = value;
                this.RaisePropertyChanged("codigoSistema");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int codigoSucursal {
            get {
                return this.codigoSucursalField;
            }
            set {
                this.codigoSucursalField = value;
                this.RaisePropertyChanged("codigoSucursal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string cufd {
            get {
                return this.cufdField;
            }
            set {
                this.cufdField = value;
                this.RaisePropertyChanged("cufd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string cuis {
            get {
                return this.cuisField;
            }
            set {
                this.cuisField = value;
                this.RaisePropertyChanged("cuis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public long nit {
            get {
                return this.nitField;
            }
            set {
                this.nitField = value;
                this.RaisePropertyChanged("nit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int tipoFacturaDocumento {
            get {
                return this.tipoFacturaDocumentoField;
            }
            set {
                this.tipoFacturaDocumentoField = value;
                this.RaisePropertyChanged("tipoFacturaDocumento");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaComunicacion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensajeServicio))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensajeRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ventaAnexo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudAnulacion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudVerificacionEstado))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionAnexos))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudValidacionRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionFactura))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionMasiva))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionPaquete))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public abstract partial class modelDto : model {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(modelDto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaComunicacion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensajeServicio))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensajeRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ventaAnexo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudAnulacion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudVerificacionEstado))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionAnexos))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudValidacionRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionFactura))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionMasiva))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionPaquete))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public abstract partial class model : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaComunicacion : modelDto {
        
        private mensajeServicio[] mensajesListField;
        
        private bool transaccionField;
        
        private bool transaccionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajesList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public mensajeServicio[] mensajesList {
            get {
                return this.mensajesListField;
            }
            set {
                this.mensajesListField = value;
                this.RaisePropertyChanged("mensajesList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool transaccion {
            get {
                return this.transaccionField;
            }
            set {
                this.transaccionField = value;
                this.RaisePropertyChanged("transaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transaccionSpecified {
            get {
                return this.transaccionFieldSpecified;
            }
            set {
                this.transaccionFieldSpecified = value;
                this.RaisePropertyChanged("transaccionSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensajeRecepcion))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class mensajeServicio : modelDto {
        
        private int codigoField;
        
        private bool codigoFieldSpecified;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoSpecified {
            get {
                return this.codigoFieldSpecified;
            }
            set {
                this.codigoFieldSpecified = value;
                this.RaisePropertyChanged("codigoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class mensajeRecepcion : mensajeServicio {
        
        private bool advertenciaField;
        
        private bool advertenciaFieldSpecified;
        
        private int numeroArchivoField;
        
        private bool numeroArchivoFieldSpecified;
        
        private int numeroDetalleField;
        
        private bool numeroDetalleFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool advertencia {
            get {
                return this.advertenciaField;
            }
            set {
                this.advertenciaField = value;
                this.RaisePropertyChanged("advertencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool advertenciaSpecified {
            get {
                return this.advertenciaFieldSpecified;
            }
            set {
                this.advertenciaFieldSpecified = value;
                this.RaisePropertyChanged("advertenciaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int numeroArchivo {
            get {
                return this.numeroArchivoField;
            }
            set {
                this.numeroArchivoField = value;
                this.RaisePropertyChanged("numeroArchivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroArchivoSpecified {
            get {
                return this.numeroArchivoFieldSpecified;
            }
            set {
                this.numeroArchivoFieldSpecified = value;
                this.RaisePropertyChanged("numeroArchivoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int numeroDetalle {
            get {
                return this.numeroDetalleField;
            }
            set {
                this.numeroDetalleField = value;
                this.RaisePropertyChanged("numeroDetalle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroDetalleSpecified {
            get {
                return this.numeroDetalleFieldSpecified;
            }
            set {
                this.numeroDetalleFieldSpecified = value;
                this.RaisePropertyChanged("numeroDetalleSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaRecepcion : modelDto {
        
        private string codigoDescripcionField;
        
        private int codigoEstadoField;
        
        private bool codigoEstadoFieldSpecified;
        
        private string codigoRecepcionField;
        
        private mensajeRecepcion[] mensajesListField;
        
        private bool transaccionField;
        
        private bool transaccionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoDescripcion {
            get {
                return this.codigoDescripcionField;
            }
            set {
                this.codigoDescripcionField = value;
                this.RaisePropertyChanged("codigoDescripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoEstado {
            get {
                return this.codigoEstadoField;
            }
            set {
                this.codigoEstadoField = value;
                this.RaisePropertyChanged("codigoEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoEstadoSpecified {
            get {
                return this.codigoEstadoFieldSpecified;
            }
            set {
                this.codigoEstadoFieldSpecified = value;
                this.RaisePropertyChanged("codigoEstadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codigoRecepcion {
            get {
                return this.codigoRecepcionField;
            }
            set {
                this.codigoRecepcionField = value;
                this.RaisePropertyChanged("codigoRecepcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajesList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public mensajeRecepcion[] mensajesList {
            get {
                return this.mensajesListField;
            }
            set {
                this.mensajesListField = value;
                this.RaisePropertyChanged("mensajesList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool transaccion {
            get {
                return this.transaccionField;
            }
            set {
                this.transaccionField = value;
                this.RaisePropertyChanged("transaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transaccionSpecified {
            get {
                return this.transaccionFieldSpecified;
            }
            set {
                this.transaccionFieldSpecified = value;
                this.RaisePropertyChanged("transaccionSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class ventaAnexo : modelDto {
        
        private string codigoField;
        
        private string codigoProductoField;
        
        private long codigoProductoSinField;
        
        private string tipoCodigoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigoProducto {
            get {
                return this.codigoProductoField;
            }
            set {
                this.codigoProductoField = value;
                this.RaisePropertyChanged("codigoProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long codigoProductoSin {
            get {
                return this.codigoProductoSinField;
            }
            set {
                this.codigoProductoSinField = value;
                this.RaisePropertyChanged("codigoProductoSin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string tipoCodigo {
            get {
                return this.tipoCodigoField;
            }
            set {
                this.tipoCodigoField = value;
                this.RaisePropertyChanged("tipoCodigo");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudAnulacion : solicitudRecepcion {
        
        private int codigoMotivoField;
        
        private string cufField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoMotivo {
            get {
                return this.codigoMotivoField;
            }
            set {
                this.codigoMotivoField = value;
                this.RaisePropertyChanged("codigoMotivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cuf {
            get {
                return this.cufField;
            }
            set {
                this.cufField = value;
                this.RaisePropertyChanged("cuf");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudVerificacionEstado : solicitudRecepcion {
        
        private string cufField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cuf {
            get {
                return this.cufField;
            }
            set {
                this.cufField = value;
                this.RaisePropertyChanged("cuf");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudRecepcionAnexos : solicitudRecepcion {
        
        private ventaAnexo[] anexosListField;
        
        private string cufField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("anexosList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ventaAnexo[] anexosList {
            get {
                return this.anexosListField;
            }
            set {
                this.anexosListField = value;
                this.RaisePropertyChanged("anexosList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cuf {
            get {
                return this.cufField;
            }
            set {
                this.cufField = value;
                this.RaisePropertyChanged("cuf");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudValidacionRecepcion : solicitudRecepcion {
        
        private string codigoRecepcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoRecepcion {
            get {
                return this.codigoRecepcionField;
            }
            set {
                this.codigoRecepcionField = value;
                this.RaisePropertyChanged("codigoRecepcion");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudRecepcionMasiva : solicitudRecepcionFactura {
        
        private int cantidadFacturasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantidadFacturas {
            get {
                return this.cantidadFacturasField;
            }
            set {
                this.cantidadFacturasField = value;
                this.RaisePropertyChanged("cantidadFacturas");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionPaqueteFactura", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class recepcionPaqueteFactura {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsFormsApp2.ServiceReference1.solicitudRecepcionPaquete SolicitudServicioRecepcionPaquete;
        
        public recepcionPaqueteFactura() {
        }
        
        public recepcionPaqueteFactura(WindowsFormsApp2.ServiceReference1.solicitudRecepcionPaquete SolicitudServicioRecepcionPaquete) {
            this.SolicitudServicioRecepcionPaquete = SolicitudServicioRecepcionPaquete;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionPaqueteFacturaResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class recepcionPaqueteFacturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsFormsApp2.ServiceReference1.respuestaRecepcion RespuestaServicioFacturacion;
        
        public recepcionPaqueteFacturaResponse() {
        }
        
        public recepcionPaqueteFacturaResponse(WindowsFormsApp2.ServiceReference1.respuestaRecepcion RespuestaServicioFacturacion) {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarComunicacion", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class verificarComunicacion {
        
        public verificarComunicacion() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarComunicacionResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class verificarComunicacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsFormsApp2.ServiceReference1.respuestaComunicacion @return;
        
        public verificarComunicacionResponse() {
        }
        
        public verificarComunicacionResponse(WindowsFormsApp2.ServiceReference1.respuestaComunicacion @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionFactura", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class recepcionFactura {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsFormsApp2.ServiceReference1.solicitudRecepcionFactura SolicitudServicioRecepcionFactura;
        
        public recepcionFactura() {
        }
        
        public recepcionFactura(WindowsFormsApp2.ServiceReference1.solicitudRecepcionFactura SolicitudServicioRecepcionFactura) {
            this.SolicitudServicioRecepcionFactura = SolicitudServicioRecepcionFactura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionFacturaResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class recepcionFacturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsFormsApp2.ServiceReference1.respuestaRecepcion RespuestaServicioFacturacion;
        
        public recepcionFacturaResponse() {
        }
        
        public recepcionFacturaResponse(WindowsFormsApp2.ServiceReference1.respuestaRecepcion RespuestaServicioFacturacion) {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validacionRecepcionMasivaFactura", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class validacionRecepcionMasivaFactura {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsFormsApp2.ServiceReference1.solicitudValidacionRecepcion SolicitudServicioValidacionRecepcionMasiva;
        
        public validacionRecepcionMasivaFactura() {
        }
        
        public validacionRecepcionMasivaFactura(WindowsFormsApp2.ServiceReference1.solicitudValidacionRecepcion SolicitudServicioValidacionRecepcionMasiva) {
            this.SolicitudServicioValidacionRecepcionMasiva = SolicitudServicioValidacionRecepcionMasiva;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validacionRecepcionMasivaFacturaResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class validacionRecepcionMasivaFacturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsFormsApp2.ServiceReference1.respuestaRecepcion RespuestaServicioFacturacion;
        
        public validacionRecepcionMasivaFacturaResponse() {
        }
        
        public validacionRecepcionMasivaFacturaResponse(WindowsFormsApp2.ServiceReference1.respuestaRecepcion RespuestaServicioFacturacion) {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionAnexos", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class recepcionAnexos {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsFormsApp2.ServiceReference1.solicitudRecepcionAnexos SolicitudRecepcionAnexos;
        
        public recepcionAnexos() {
        }
        
        public recepcionAnexos(WindowsFormsApp2.ServiceReference1.solicitudRecepcionAnexos SolicitudRecepcionAnexos) {
            this.SolicitudRecepcionAnexos = SolicitudRecepcionAnexos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionAnexosResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class recepcionAnexosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsFormsApp2.ServiceReference1.respuestaRecepcion RespuestaRecepcionAnexos;
        
        public recepcionAnexosResponse() {
        }
        
        public recepcionAnexosResponse(WindowsFormsApp2.ServiceReference1.respuestaRecepcion RespuestaRecepcionAnexos) {
            this.RespuestaRecepcionAnexos = RespuestaRecepcionAnexos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionMasivaFactura", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class recepcionMasivaFactura {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsFormsApp2.ServiceReference1.solicitudRecepcionMasiva SolicitudServicioRecepcionMasiva;
        
        public recepcionMasivaFactura() {
        }
        
        public recepcionMasivaFactura(WindowsFormsApp2.ServiceReference1.solicitudRecepcionMasiva SolicitudServicioRecepcionMasiva) {
            this.SolicitudServicioRecepcionMasiva = SolicitudServicioRecepcionMasiva;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionMasivaFacturaResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class recepcionMasivaFacturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsFormsApp2.ServiceReference1.respuestaRecepcion RespuestaServicioFacturacion;
        
        public recepcionMasivaFacturaResponse() {
        }
        
        public recepcionMasivaFacturaResponse(WindowsFormsApp2.ServiceReference1.respuestaRecepcion RespuestaServicioFacturacion) {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificacionEstadoFactura", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class verificacionEstadoFactura {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsFormsApp2.ServiceReference1.solicitudVerificacionEstado SolicitudServicioVerificacionEstadoFactura;
        
        public verificacionEstadoFactura() {
        }
        
        public verificacionEstadoFactura(WindowsFormsApp2.ServiceReference1.solicitudVerificacionEstado SolicitudServicioVerificacionEstadoFactura) {
            this.SolicitudServicioVerificacionEstadoFactura = SolicitudServicioVerificacionEstadoFactura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificacionEstadoFacturaResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class verificacionEstadoFacturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsFormsApp2.ServiceReference1.respuestaRecepcion RespuestaServicioFacturacion;
        
        public verificacionEstadoFacturaResponse() {
        }
        
        public verificacionEstadoFacturaResponse(WindowsFormsApp2.ServiceReference1.respuestaRecepcion RespuestaServicioFacturacion) {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validacionRecepcionPaqueteFactura", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class validacionRecepcionPaqueteFactura {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsFormsApp2.ServiceReference1.solicitudValidacionRecepcion SolicitudServicioValidacionRecepcionPaquete;
        
        public validacionRecepcionPaqueteFactura() {
        }
        
        public validacionRecepcionPaqueteFactura(WindowsFormsApp2.ServiceReference1.solicitudValidacionRecepcion SolicitudServicioValidacionRecepcionPaquete) {
            this.SolicitudServicioValidacionRecepcionPaquete = SolicitudServicioValidacionRecepcionPaquete;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validacionRecepcionPaqueteFacturaResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class validacionRecepcionPaqueteFacturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsFormsApp2.ServiceReference1.respuestaRecepcion RespuestaServicioFacturacion;
        
        public validacionRecepcionPaqueteFacturaResponse() {
        }
        
        public validacionRecepcionPaqueteFacturaResponse(WindowsFormsApp2.ServiceReference1.respuestaRecepcion RespuestaServicioFacturacion) {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="anulacionFactura", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class anulacionFactura {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsFormsApp2.ServiceReference1.solicitudAnulacion SolicitudServicioAnulacionFactura;
        
        public anulacionFactura() {
        }
        
        public anulacionFactura(WindowsFormsApp2.ServiceReference1.solicitudAnulacion SolicitudServicioAnulacionFactura) {
            this.SolicitudServicioAnulacionFactura = SolicitudServicioAnulacionFactura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="anulacionFacturaResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class anulacionFacturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WindowsFormsApp2.ServiceReference1.respuestaRecepcion RespuestaServicioFacturacion;
        
        public anulacionFacturaResponse() {
        }
        
        public anulacionFacturaResponse(WindowsFormsApp2.ServiceReference1.respuestaRecepcion RespuestaServicioFacturacion) {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioFacturacionChannel : WindowsFormsApp2.ServiceReference1.ServicioFacturacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioFacturacionClient : System.ServiceModel.ClientBase<WindowsFormsApp2.ServiceReference1.ServicioFacturacion>, WindowsFormsApp2.ServiceReference1.ServicioFacturacion {
        
        public ServicioFacturacionClient() {
        }
        
        public ServicioFacturacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioFacturacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioFacturacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioFacturacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp2.ServiceReference1.recepcionPaqueteFacturaResponse WindowsFormsApp2.ServiceReference1.ServicioFacturacion.recepcionPaqueteFactura(WindowsFormsApp2.ServiceReference1.recepcionPaqueteFactura request) {
            return base.Channel.recepcionPaqueteFactura(request);
        }
        
        public WindowsFormsApp2.ServiceReference1.respuestaRecepcion recepcionPaqueteFactura(WindowsFormsApp2.ServiceReference1.solicitudRecepcionPaquete SolicitudServicioRecepcionPaquete) {
            WindowsFormsApp2.ServiceReference1.recepcionPaqueteFactura inValue = new WindowsFormsApp2.ServiceReference1.recepcionPaqueteFactura();
            inValue.SolicitudServicioRecepcionPaquete = SolicitudServicioRecepcionPaquete;
            WindowsFormsApp2.ServiceReference1.recepcionPaqueteFacturaResponse retVal = ((WindowsFormsApp2.ServiceReference1.ServicioFacturacion)(this)).recepcionPaqueteFactura(inValue);
            return retVal.RespuestaServicioFacturacion;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.recepcionPaqueteFacturaResponse> WindowsFormsApp2.ServiceReference1.ServicioFacturacion.recepcionPaqueteFacturaAsync(WindowsFormsApp2.ServiceReference1.recepcionPaqueteFactura request) {
            return base.Channel.recepcionPaqueteFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.recepcionPaqueteFacturaResponse> recepcionPaqueteFacturaAsync(WindowsFormsApp2.ServiceReference1.solicitudRecepcionPaquete SolicitudServicioRecepcionPaquete) {
            WindowsFormsApp2.ServiceReference1.recepcionPaqueteFactura inValue = new WindowsFormsApp2.ServiceReference1.recepcionPaqueteFactura();
            inValue.SolicitudServicioRecepcionPaquete = SolicitudServicioRecepcionPaquete;
            return ((WindowsFormsApp2.ServiceReference1.ServicioFacturacion)(this)).recepcionPaqueteFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp2.ServiceReference1.verificarComunicacionResponse WindowsFormsApp2.ServiceReference1.ServicioFacturacion.verificarComunicacion(WindowsFormsApp2.ServiceReference1.verificarComunicacion request) {
            return base.Channel.verificarComunicacion(request);
        }
        
        public WindowsFormsApp2.ServiceReference1.respuestaComunicacion verificarComunicacion() {
            WindowsFormsApp2.ServiceReference1.verificarComunicacion inValue = new WindowsFormsApp2.ServiceReference1.verificarComunicacion();
            WindowsFormsApp2.ServiceReference1.verificarComunicacionResponse retVal = ((WindowsFormsApp2.ServiceReference1.ServicioFacturacion)(this)).verificarComunicacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.verificarComunicacionResponse> WindowsFormsApp2.ServiceReference1.ServicioFacturacion.verificarComunicacionAsync(WindowsFormsApp2.ServiceReference1.verificarComunicacion request) {
            return base.Channel.verificarComunicacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.verificarComunicacionResponse> verificarComunicacionAsync() {
            WindowsFormsApp2.ServiceReference1.verificarComunicacion inValue = new WindowsFormsApp2.ServiceReference1.verificarComunicacion();
            return ((WindowsFormsApp2.ServiceReference1.ServicioFacturacion)(this)).verificarComunicacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp2.ServiceReference1.recepcionFacturaResponse WindowsFormsApp2.ServiceReference1.ServicioFacturacion.recepcionFactura(WindowsFormsApp2.ServiceReference1.recepcionFactura request) {
            return base.Channel.recepcionFactura(request);
        }
        
        public WindowsFormsApp2.ServiceReference1.respuestaRecepcion recepcionFactura(WindowsFormsApp2.ServiceReference1.solicitudRecepcionFactura SolicitudServicioRecepcionFactura) {
            WindowsFormsApp2.ServiceReference1.recepcionFactura inValue = new WindowsFormsApp2.ServiceReference1.recepcionFactura();
            inValue.SolicitudServicioRecepcionFactura = SolicitudServicioRecepcionFactura;
            WindowsFormsApp2.ServiceReference1.recepcionFacturaResponse retVal = ((WindowsFormsApp2.ServiceReference1.ServicioFacturacion)(this)).recepcionFactura(inValue);
            return retVal.RespuestaServicioFacturacion;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.recepcionFacturaResponse> WindowsFormsApp2.ServiceReference1.ServicioFacturacion.recepcionFacturaAsync(WindowsFormsApp2.ServiceReference1.recepcionFactura request) {
            return base.Channel.recepcionFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.recepcionFacturaResponse> recepcionFacturaAsync(WindowsFormsApp2.ServiceReference1.solicitudRecepcionFactura SolicitudServicioRecepcionFactura) {
            WindowsFormsApp2.ServiceReference1.recepcionFactura inValue = new WindowsFormsApp2.ServiceReference1.recepcionFactura();
            inValue.SolicitudServicioRecepcionFactura = SolicitudServicioRecepcionFactura;
            return ((WindowsFormsApp2.ServiceReference1.ServicioFacturacion)(this)).recepcionFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp2.ServiceReference1.validacionRecepcionMasivaFacturaResponse WindowsFormsApp2.ServiceReference1.ServicioFacturacion.validacionRecepcionMasivaFactura(WindowsFormsApp2.ServiceReference1.validacionRecepcionMasivaFactura request) {
            return base.Channel.validacionRecepcionMasivaFactura(request);
        }
        
        public WindowsFormsApp2.ServiceReference1.respuestaRecepcion validacionRecepcionMasivaFactura(WindowsFormsApp2.ServiceReference1.solicitudValidacionRecepcion SolicitudServicioValidacionRecepcionMasiva) {
            WindowsFormsApp2.ServiceReference1.validacionRecepcionMasivaFactura inValue = new WindowsFormsApp2.ServiceReference1.validacionRecepcionMasivaFactura();
            inValue.SolicitudServicioValidacionRecepcionMasiva = SolicitudServicioValidacionRecepcionMasiva;
            WindowsFormsApp2.ServiceReference1.validacionRecepcionMasivaFacturaResponse retVal = ((WindowsFormsApp2.ServiceReference1.ServicioFacturacion)(this)).validacionRecepcionMasivaFactura(inValue);
            return retVal.RespuestaServicioFacturacion;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.validacionRecepcionMasivaFacturaResponse> WindowsFormsApp2.ServiceReference1.ServicioFacturacion.validacionRecepcionMasivaFacturaAsync(WindowsFormsApp2.ServiceReference1.validacionRecepcionMasivaFactura request) {
            return base.Channel.validacionRecepcionMasivaFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.validacionRecepcionMasivaFacturaResponse> validacionRecepcionMasivaFacturaAsync(WindowsFormsApp2.ServiceReference1.solicitudValidacionRecepcion SolicitudServicioValidacionRecepcionMasiva) {
            WindowsFormsApp2.ServiceReference1.validacionRecepcionMasivaFactura inValue = new WindowsFormsApp2.ServiceReference1.validacionRecepcionMasivaFactura();
            inValue.SolicitudServicioValidacionRecepcionMasiva = SolicitudServicioValidacionRecepcionMasiva;
            return ((WindowsFormsApp2.ServiceReference1.ServicioFacturacion)(this)).validacionRecepcionMasivaFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp2.ServiceReference1.recepcionAnexosResponse WindowsFormsApp2.ServiceReference1.ServicioFacturacion.recepcionAnexos(WindowsFormsApp2.ServiceReference1.recepcionAnexos request) {
            return base.Channel.recepcionAnexos(request);
        }
        
        public WindowsFormsApp2.ServiceReference1.respuestaRecepcion recepcionAnexos(WindowsFormsApp2.ServiceReference1.solicitudRecepcionAnexos SolicitudRecepcionAnexos) {
            WindowsFormsApp2.ServiceReference1.recepcionAnexos inValue = new WindowsFormsApp2.ServiceReference1.recepcionAnexos();
            inValue.SolicitudRecepcionAnexos = SolicitudRecepcionAnexos;
            WindowsFormsApp2.ServiceReference1.recepcionAnexosResponse retVal = ((WindowsFormsApp2.ServiceReference1.ServicioFacturacion)(this)).recepcionAnexos(inValue);
            return retVal.RespuestaRecepcionAnexos;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.recepcionAnexosResponse> WindowsFormsApp2.ServiceReference1.ServicioFacturacion.recepcionAnexosAsync(WindowsFormsApp2.ServiceReference1.recepcionAnexos request) {
            return base.Channel.recepcionAnexosAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.recepcionAnexosResponse> recepcionAnexosAsync(WindowsFormsApp2.ServiceReference1.solicitudRecepcionAnexos SolicitudRecepcionAnexos) {
            WindowsFormsApp2.ServiceReference1.recepcionAnexos inValue = new WindowsFormsApp2.ServiceReference1.recepcionAnexos();
            inValue.SolicitudRecepcionAnexos = SolicitudRecepcionAnexos;
            return ((WindowsFormsApp2.ServiceReference1.ServicioFacturacion)(this)).recepcionAnexosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp2.ServiceReference1.recepcionMasivaFacturaResponse WindowsFormsApp2.ServiceReference1.ServicioFacturacion.recepcionMasivaFactura(WindowsFormsApp2.ServiceReference1.recepcionMasivaFactura request) {
            return base.Channel.recepcionMasivaFactura(request);
        }
        
        public WindowsFormsApp2.ServiceReference1.respuestaRecepcion recepcionMasivaFactura(WindowsFormsApp2.ServiceReference1.solicitudRecepcionMasiva SolicitudServicioRecepcionMasiva) {
            WindowsFormsApp2.ServiceReference1.recepcionMasivaFactura inValue = new WindowsFormsApp2.ServiceReference1.recepcionMasivaFactura();
            inValue.SolicitudServicioRecepcionMasiva = SolicitudServicioRecepcionMasiva;
            WindowsFormsApp2.ServiceReference1.recepcionMasivaFacturaResponse retVal = ((WindowsFormsApp2.ServiceReference1.ServicioFacturacion)(this)).recepcionMasivaFactura(inValue);
            return retVal.RespuestaServicioFacturacion;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.recepcionMasivaFacturaResponse> WindowsFormsApp2.ServiceReference1.ServicioFacturacion.recepcionMasivaFacturaAsync(WindowsFormsApp2.ServiceReference1.recepcionMasivaFactura request) {
            return base.Channel.recepcionMasivaFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.recepcionMasivaFacturaResponse> recepcionMasivaFacturaAsync(WindowsFormsApp2.ServiceReference1.solicitudRecepcionMasiva SolicitudServicioRecepcionMasiva) {
            WindowsFormsApp2.ServiceReference1.recepcionMasivaFactura inValue = new WindowsFormsApp2.ServiceReference1.recepcionMasivaFactura();
            inValue.SolicitudServicioRecepcionMasiva = SolicitudServicioRecepcionMasiva;
            return ((WindowsFormsApp2.ServiceReference1.ServicioFacturacion)(this)).recepcionMasivaFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp2.ServiceReference1.verificacionEstadoFacturaResponse WindowsFormsApp2.ServiceReference1.ServicioFacturacion.verificacionEstadoFactura(WindowsFormsApp2.ServiceReference1.verificacionEstadoFactura request) {
            return base.Channel.verificacionEstadoFactura(request);
        }
        
        public WindowsFormsApp2.ServiceReference1.respuestaRecepcion verificacionEstadoFactura(WindowsFormsApp2.ServiceReference1.solicitudVerificacionEstado SolicitudServicioVerificacionEstadoFactura) {
            WindowsFormsApp2.ServiceReference1.verificacionEstadoFactura inValue = new WindowsFormsApp2.ServiceReference1.verificacionEstadoFactura();
            inValue.SolicitudServicioVerificacionEstadoFactura = SolicitudServicioVerificacionEstadoFactura;
            WindowsFormsApp2.ServiceReference1.verificacionEstadoFacturaResponse retVal = ((WindowsFormsApp2.ServiceReference1.ServicioFacturacion)(this)).verificacionEstadoFactura(inValue);
            return retVal.RespuestaServicioFacturacion;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.verificacionEstadoFacturaResponse> WindowsFormsApp2.ServiceReference1.ServicioFacturacion.verificacionEstadoFacturaAsync(WindowsFormsApp2.ServiceReference1.verificacionEstadoFactura request) {
            return base.Channel.verificacionEstadoFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.verificacionEstadoFacturaResponse> verificacionEstadoFacturaAsync(WindowsFormsApp2.ServiceReference1.solicitudVerificacionEstado SolicitudServicioVerificacionEstadoFactura) {
            WindowsFormsApp2.ServiceReference1.verificacionEstadoFactura inValue = new WindowsFormsApp2.ServiceReference1.verificacionEstadoFactura();
            inValue.SolicitudServicioVerificacionEstadoFactura = SolicitudServicioVerificacionEstadoFactura;
            return ((WindowsFormsApp2.ServiceReference1.ServicioFacturacion)(this)).verificacionEstadoFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp2.ServiceReference1.validacionRecepcionPaqueteFacturaResponse WindowsFormsApp2.ServiceReference1.ServicioFacturacion.validacionRecepcionPaqueteFactura(WindowsFormsApp2.ServiceReference1.validacionRecepcionPaqueteFactura request) {
            return base.Channel.validacionRecepcionPaqueteFactura(request);
        }
        
        public WindowsFormsApp2.ServiceReference1.respuestaRecepcion validacionRecepcionPaqueteFactura(WindowsFormsApp2.ServiceReference1.solicitudValidacionRecepcion SolicitudServicioValidacionRecepcionPaquete) {
            WindowsFormsApp2.ServiceReference1.validacionRecepcionPaqueteFactura inValue = new WindowsFormsApp2.ServiceReference1.validacionRecepcionPaqueteFactura();
            inValue.SolicitudServicioValidacionRecepcionPaquete = SolicitudServicioValidacionRecepcionPaquete;
            WindowsFormsApp2.ServiceReference1.validacionRecepcionPaqueteFacturaResponse retVal = ((WindowsFormsApp2.ServiceReference1.ServicioFacturacion)(this)).validacionRecepcionPaqueteFactura(inValue);
            return retVal.RespuestaServicioFacturacion;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.validacionRecepcionPaqueteFacturaResponse> WindowsFormsApp2.ServiceReference1.ServicioFacturacion.validacionRecepcionPaqueteFacturaAsync(WindowsFormsApp2.ServiceReference1.validacionRecepcionPaqueteFactura request) {
            return base.Channel.validacionRecepcionPaqueteFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.validacionRecepcionPaqueteFacturaResponse> validacionRecepcionPaqueteFacturaAsync(WindowsFormsApp2.ServiceReference1.solicitudValidacionRecepcion SolicitudServicioValidacionRecepcionPaquete) {
            WindowsFormsApp2.ServiceReference1.validacionRecepcionPaqueteFactura inValue = new WindowsFormsApp2.ServiceReference1.validacionRecepcionPaqueteFactura();
            inValue.SolicitudServicioValidacionRecepcionPaquete = SolicitudServicioValidacionRecepcionPaquete;
            return ((WindowsFormsApp2.ServiceReference1.ServicioFacturacion)(this)).validacionRecepcionPaqueteFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp2.ServiceReference1.anulacionFacturaResponse WindowsFormsApp2.ServiceReference1.ServicioFacturacion.anulacionFactura(WindowsFormsApp2.ServiceReference1.anulacionFactura request) {
            return base.Channel.anulacionFactura(request);
        }
        
        public WindowsFormsApp2.ServiceReference1.respuestaRecepcion anulacionFactura(WindowsFormsApp2.ServiceReference1.solicitudAnulacion SolicitudServicioAnulacionFactura) {
            WindowsFormsApp2.ServiceReference1.anulacionFactura inValue = new WindowsFormsApp2.ServiceReference1.anulacionFactura();
            inValue.SolicitudServicioAnulacionFactura = SolicitudServicioAnulacionFactura;
            WindowsFormsApp2.ServiceReference1.anulacionFacturaResponse retVal = ((WindowsFormsApp2.ServiceReference1.ServicioFacturacion)(this)).anulacionFactura(inValue);
            return retVal.RespuestaServicioFacturacion;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.anulacionFacturaResponse> WindowsFormsApp2.ServiceReference1.ServicioFacturacion.anulacionFacturaAsync(WindowsFormsApp2.ServiceReference1.anulacionFactura request) {
            return base.Channel.anulacionFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.anulacionFacturaResponse> anulacionFacturaAsync(WindowsFormsApp2.ServiceReference1.solicitudAnulacion SolicitudServicioAnulacionFactura) {
            WindowsFormsApp2.ServiceReference1.anulacionFactura inValue = new WindowsFormsApp2.ServiceReference1.anulacionFactura();
            inValue.SolicitudServicioAnulacionFactura = SolicitudServicioAnulacionFactura;
            return ((WindowsFormsApp2.ServiceReference1.ServicioFacturacion)(this)).anulacionFacturaAsync(inValue);
        }
    }
}
